FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir gunicorn

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["gunicorn", "klyro_backend.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "2"]

